import html as _html
import logging
import secrets
import requests
from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class EssServer(models.Model):
    """
    ESS Client Server registry.

    One record per client Odoo installation that has ess_hr_client installed.
    The admin server periodically pulls stats from each client to enforce limits.
    """
    _name = 'ess.server'
    _description = 'ESS Client Server'
    _rec_name = 'name'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    name = fields.Char(string='Server Name', required=True, tracking=True)
    url = fields.Char(
        string='Server URL',
        required=True,
        tracking=True,
        help='Base URL of the client Odoo server (e.g. https://company.odoo.com). '
             'Trailing slashes are ignored during validation.',
    )
    # ── License link ──────────────────────────────────────────────────────────
    license_id = fields.Many2one(
        'ess.license',
        string='License',
        ondelete='set null',
        tracking=True,
    )

    # ── Admin connection key ──────────────────────────────────────────────────
    connection_key = fields.Char(
        string='Admin Connection Key',
        copy=False,
        help='Secret key sent with every stats sync request (X-ESS-Admin-Key header). '
             'Must match the value set in ESS Client → Configuration → Settings.',
    )

    # ── Per-server settings ───────────────────────────────────────────────────
    auto_logout_duration = fields.Integer(
        string='Auto Logout Duration',
        default=72,
        tracking=True,
        help='Duration of inactivity before the mobile app auto-logs out. '
             'Unit is controlled by the field below. Sent to the mobile app on each Step 1 validation.',
    )
    auto_logout_unit = fields.Selection(
        selection=[('hours', 'Hours'), ('minutes', 'Minutes')],
        string='Unit',
        default='hours',
        required=True,
        tracking=True,
        help='Unit for the Auto Logout Duration above.',
    )

    # ── Live stats (fetched from client) ──────────────────────────────────────
    employee_count = fields.Integer(
        string='Employee Count', readonly=True, default=0,
        help='Number of active employees on the client server (last sync).',
    )
    active_user_count = fields.Integer(
        string='Active Users (30d)', readonly=True, default=0,
        help='Employees who used the mobile app in the last 30 days (last sync).',
    )
    odoo_user_count = fields.Integer(
        string='Total Odoo Users', readonly=True, default=0,
    )
    internal_user_count = fields.Integer(
        string='Internal Users', readonly=True, default=0,
    )
    portal_user_count = fields.Integer(
        string='Portal Users', readonly=True, default=0,
    )
    public_user_count = fields.Integer(
        string='Public Users', readonly=True, default=0,
    )
    archived_user_count = fields.Integer(
        string='Archived Users', readonly=True, default=0,
    )
    module_ids = fields.One2many(
        'ess.server.module', 'server_id', string='Installed Modules', readonly=True,
    )
    last_sync_date = fields.Datetime(string='Last Sync', readonly=True)
    last_sync_status = fields.Selection(
        selection=[
            ('success', 'Success'),
            ('failed', 'Failed'),
            ('unreachable', 'Unreachable'),
        ],
        string='Last Sync Status',
        readonly=True,
    )
    last_sync_error = fields.Text(string='Last Sync Error', readonly=True)

    # ── Server status ─────────────────────────────────────────────────────────
    server_status = fields.Selection(
        selection=[
            ('active', 'Active'),
            ('unreachable', 'Unreachable'),
            ('deactivated', 'Deactivated'),
        ],
        string='Status',
        default='active',
        readonly=True,
        tracking=True,
    )

    # ── Scan report (populated by the Scan button) ────────────────────────────
    scan_html = fields.Html(
        string='Scan Report',
        readonly=True,
        sanitize=False,
        help='Full health-check report generated by the Scan button.',
    )
    scan_date = fields.Datetime(string='Last Scan', readonly=True)

    # ── Module check result (populated after each sync) ───────────────────────
    module_check_html = fields.Html(
        string='Module Check',
        readonly=True,
        sanitize=False,
        help='Comparison of license allowed modules vs modules installed on this server (updated on sync).',
    )

    # ── Status history ────────────────────────────────────────────────────────
    history_ids = fields.One2many(
        'ess.server.history', 'server_id', string='Status History', readonly=True,
    )

    _url_unique = models.Constraint(
        'UNIQUE(url)',
        'A server URL must be unique.',
    )

    # ── Status wizard ─────────────────────────────────────────────────────────

    def action_open_status_wizard(self):
        """Open the Change Status wizard pre-filled with this server."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Change Server Status'),
            'res_model': 'ess.server.status.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_server_id': self.id,
                'default_new_status': self.server_status,
            },
        }

    # ── Key generation ────────────────────────────────────────────────────────

    def action_generate_key(self):
        """Generate a new cryptographically secure connection key (256-bit)."""
        self.ensure_one()
        self.sudo().write({'connection_key': secrets.token_urlsafe(32)})
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Key Generated'),
                'message': _('New connection key generated. Copy it and paste it into Odoo Settings → ESS Client → Admin Connection Key → Save.'),
                'sticky': True,
                'type': 'warning',
                'next': {
                    'type': 'ir.actions.act_window',
                    'res_model': self._name,
                    'res_id': self.id,
                    'view_mode': 'form',
                    'views': [[False, 'form']],
                    'target': 'current',
                },
            },
        }

    # ── Force logout ──────────────────────────────────────────────────────────

    def action_force_logout(self):
        """Send a force-logout signal to the client server."""
        self.ensure_one()
        result = self._call_admin_endpoint('force-logout')
        reload = self._reload_action()
        if result.get('ok'):
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Force Logout Activated'),
                    'message': _('All mobile users on this server will be logged out on their next request.'),
                    'sticky': False,
                    'type': 'warning',
                    'next': reload,
                },
            }
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Force Logout Failed'),
                'message': result.get('message', _('Could not reach the client server.')),
                'sticky': True,
                'type': 'danger',
                'next': reload,
            },
        }

    def _call_admin_endpoint(self, path):
        """
        POST to /ess/api/admin/<path> on this server using the connection key.
        Returns {'ok': True} or {'ok': False, 'message': str}.
        """
        self.ensure_one()
        url = self._normalize_url(self.url) + '/ess/api/admin/' + path
        headers = {'Content-Type': 'application/json'}
        if self.connection_key:
            headers['X-ESS-Admin-Key'] = self.connection_key
        try:
            resp = requests.post(url, headers=headers, timeout=15)
            if resp.status_code == 401:
                return {'ok': False, 'message': _(
                    'Authentication failed (401). The connection key does not match.'
                )}
            if resp.status_code != 200:
                return {'ok': False, 'message': _(
                    'Unexpected response from client server: %d %s.'
                ) % (resp.status_code, resp.reason)}
            data = resp.json()
            if not data.get('success'):
                err = data.get('error', {})
                return {'ok': False, 'message': err.get('message') or str(data)}
            return {'ok': True}
        except requests.exceptions.ConnectionError:
            return {'ok': False, 'message': _(
                'Cannot reach the server at %s. Check the URL and network.'
            ) % self.url}
        except requests.exceptions.Timeout:
            return {'ok': False, 'message': _(
                'Connection timed out after 15 seconds (%s).'
            ) % self.url}
        except Exception as exc:
            _logger.error('ESS Admin: %s failed for %s: %s', path, self.url, exc)
            return {'ok': False, 'message': _('Unexpected error: %s') % str(exc)}

    def _reload_action(self):
        return {
            'type': 'ir.actions.act_window',
            'res_model': self._name,
            'res_id': self.id,
            'view_mode': 'form',
            'views': [[False, 'form']],
            'target': 'current',
        }

    # ── Manual sync action ────────────────────────────────────────────────────

    def action_sync_stats(self):
        """Manual trigger: pull stats from this server and show a specific result notification."""
        self.ensure_one()
        result = self._sync_stats()
        reload = {
            'type': 'ir.actions.act_window',
            'res_model': self._name,
            'res_id': self.id,
            'view_mode': 'form',
            'views': [[False, 'form']],
            'target': 'current',
        }

        if result.get('ok'):
            if result.get('limit_exceeded'):
                return {
                    'type': 'ir.actions.client',
                    'tag': 'display_notification',
                    'params': {
                        'title': _('Employee Limit Exceeded'),
                        'message': _(
                            'Sync succeeded but the employee limit is exceeded '
                            '(%d employees on this server). The license has been deactivated.'
                        ) % result['employee_count'],
                        'sticky': True,
                        'type': 'danger',
                        'next': reload,
                    },
                }
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Sync Successful'),
                    'message': _('%d employees · %d active mobile users (last 30 days).') % (
                        result['employee_count'], result['active_user_count']
                    ),
                    'sticky': False,
                    'type': 'success',
                    'next': reload,
                },
            }

        _TITLES = {
            'AUTH_FAILED':       _('Wrong Connection Key'),
            'ENDPOINT_NOT_FOUND': _('Client Module Not Found'),
            'SERVER_ERROR':      _('Client Server Error'),
            'HTTP_ERROR':        _('Unexpected HTTP Response'),
            'RESPONSE_ERROR':    _('Invalid Response from Client'),
            'UNREACHABLE':       _('Server Unreachable'),
            'TIMEOUT':           _('Connection Timed Out'),
            'UNEXPECTED':        _('Sync Failed'),
        }
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _TITLES.get(result.get('error_type'), _('Sync Failed')),
                'message': result.get('message', _('An unknown error occurred.')),
                'sticky': True,
                'type': 'danger',
                'next': reload,
            },
        }

    # ── Scan action ───────────────────────────────────────────────────────────

    def action_scan(self):
        """
        Fetch-only health check — does NOT deactivate, update stats, or write any sync fields.
        Calls _fetch_stats_for_scan() (read-only) then builds the report in the Scan tab.
        """
        self.ensure_one()
        fetch_result = self._fetch_stats_for_scan()
        self._build_scan_report(fetch_result)
        reload = self._reload_action()
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Scan Complete'),
                'message': _('Health-check results are available in the Scan tab.'),
                'sticky': False,
                'type': 'info',
                'next': reload,
            },
        }

    def _fetch_stats_for_scan(self):
        """
        Read-only fetch from the client's /ess/api/stats endpoint.
        Uses the same connection key as _sync_stats() but writes NOTHING to the database.
        Returns {'ok': True, 'employee_count': int, 'active_user_count': int,
                 'installed_modules': [{'name', 'technical_name', 'version'}, ...]}
        or      {'ok': False, 'error_type': str, 'message': str}.
        """
        self.ensure_one()
        stats_url = self._normalize_url(self.url) + '/ess/api/stats'
        headers = {}
        if self.connection_key:
            headers['X-ESS-Admin-Key'] = self.connection_key

        try:
            resp = requests.get(stats_url, headers=headers, timeout=15)

            if resp.status_code == 401:
                return {'ok': False, 'error_type': 'AUTH_FAILED', 'message': (
                    'Authentication failed (401). '
                    'The connection key on this server record does not match the key '
                    'set in ESS Client -> Configuration -> Settings.'
                )}
            if resp.status_code == 404:
                return {'ok': False, 'error_type': 'ENDPOINT_NOT_FOUND', 'message': (
                    'Stats endpoint not found (404). '
                    'Confirm that ess_hr_client is installed on the client server '
                    'and that the server URL is correct (%s).' % self.url
                )}
            if resp.status_code >= 500:
                return {'ok': False, 'error_type': 'SERVER_ERROR', 'message': (
                    'The client server returned an internal error (%d). '
                    'Check the Odoo logs on the client server for details.' % resp.status_code
                )}
            if resp.status_code != 200:
                return {'ok': False, 'error_type': 'HTTP_ERROR', 'message': (
                    'Unexpected HTTP response: %d %s.' % (resp.status_code, resp.reason)
                )}

            data = resp.json()
            if not data.get('success'):
                err = data.get('error', {})
                return {'ok': False, 'error_type': 'RESPONSE_ERROR', 'message': (
                    'Client returned a failure: %s' % (err.get('message') or str(data))
                )}

            stats = data.get('data', {})
            return {
                'ok': True,
                'employee_count':    int(stats.get('employee_count', 0)),
                'active_user_count': int(stats.get('active_user_count', 0)),
                'odoo_user_count':   int(stats.get('odoo_user_count', 0)),
                'internal_user_count': int(stats.get('internal_user_count', 0)),
                'portal_user_count': int(stats.get('portal_user_count', 0)),
                'public_user_count': int(stats.get('public_user_count', 0)),
                'archived_user_count': int(stats.get('archived_user_count', 0)),
                'installed_modules': stats.get('installed_modules', []),
            }

        except requests.exceptions.ConnectionError:
            return {'ok': False, 'error_type': 'UNREACHABLE', 'message': (
                'Cannot reach the server at %s. '
                'Check that the URL is correct and the Odoo server is running.' % self.url
            )}
        except requests.exceptions.Timeout:
            return {'ok': False, 'error_type': 'TIMEOUT', 'message': (
                'Connection timed out after 15 seconds. '
                'The server at %s is not responding.' % self.url
            )}
        except Exception as exc:
            _logger.error('ESS Admin: scan fetch failed for %s: %s', self.url, exc)
            return {'ok': False, 'error_type': 'UNEXPECTED', 'message': (
                'Unexpected error during scan: %s' % str(exc)
            )}

    def _build_scan_report(self, fetch_result):
        """Build a rich HTML health-check report from _fetch_stats_for_scan() result and save it to scan_html."""
        self.ensure_one()

        def esc(v):
            return _html.escape(str(v or ''))

        scan_time = fields.Datetime.now()
        issues = []   # list of (fa_icon, title, detail_html)
        warnings = []

        _ERROR_MAP = {
            'AUTH_FAILED':        ('fa-key',               'Wrong Connection Key'),
            'ENDPOINT_NOT_FOUND': ('fa-puzzle-piece',      'Client Module Not Found'),
            'SERVER_ERROR':       ('fa-server',            'Client Server Error'),
            'HTTP_ERROR':         ('fa-exchange',          'Unexpected HTTP Response'),
            'RESPONSE_ERROR':     ('fa-file-code-o',       'Invalid Response from Client'),
            'UNREACHABLE':        ('fa-plug',              'Server Unreachable'),
            'TIMEOUT':            ('fa-clock-o',           'Connection Timed Out'),
            'UNEXPECTED':         ('fa-exclamation-circle','Unexpected Error'),
        }

        if not fetch_result.get('ok'):
            icon, label = _ERROR_MAP.get(
                fetch_result.get('error_type', 'UNEXPECTED'),
                ('fa-times-circle', 'Scan Failed'),
            )
            issues.append((icon, label, esc(fetch_result.get('message', 'An unknown error occurred.'))))
        else:
            emp = fetch_result.get('employee_count', 0)
            active_users = fetch_result.get('active_user_count', 0)
            odoo_users = fetch_result.get('odoo_user_count', 0)
            internal_users = fetch_result.get('internal_user_count', 0)
            portal_users = fetch_result.get('portal_user_count', 0)
            public_users = fetch_result.get('public_user_count', 0)
            archived_users = fetch_result.get('archived_user_count', 0)
            installed_modules = fetch_result.get('installed_modules', [])
            installed_names = {
                m.get('technical_name') for m in installed_modules if m.get('technical_name')
            }
            license_rec = self.license_id

            if not license_rec:
                issues.append(('fa-ban', 'No License Assigned',
                    'This server has no license linked. Assign a license to enable mobile access.'))
            else:
                if not license_rec.active:
                    issues.append(('fa-times-circle', 'License Inactive',
                        esc(license_rec.deactivation_reason or 'License has been deactivated.')))
                elif license_rec._is_expired():
                    issues.append(('fa-calendar-times-o', 'License Expired',
                        f'License expired on <strong>{esc(str(license_rec.expiry_date))}</strong>.'))

                hard_limit = license_rec.max_employees + license_rec.employee_overage_allowed
                if emp > hard_limit:
                    issues.append(('fa-users', 'Employee Limit Exceeded',
                        f'<strong>{emp}</strong> employees found — hard limit is '
                        f'<strong>{hard_limit}</strong> '
                        f'({license_rec.max_employees} max + {license_rec.employee_overage_allowed} overage).'))
                elif emp > license_rec.max_employees:
                    warnings.append(('fa-exclamation-triangle', 'Approaching Employee Limit',
                        f'<strong>{emp}</strong> employees — over base limit of '
                        f'<strong>{license_rec.max_employees}</strong> but within the '
                        f'<strong>{license_rec.employee_overage_allowed}</strong>-employee overage '
                        f'(hard limit: {hard_limit}).'))

                if license_rec.module_ids:
                    for m in license_rec.module_ids:
                        if m.technical_name and m.technical_name not in installed_names:
                            issues.append(('fa-puzzle-piece',
                                f'Module Not Installed: {esc(m.name)}',
                                f'Allowed module <code>{esc(m.technical_name)}</code> is required by '
                                f'the license but is not installed on this server.'))

        # ── Banner ────────────────────────────────────────────────────────────
        n_issues = len(issues)
        n_warnings = len(warnings)
        if n_issues:
            b_cls, b_icon = 'alert-danger', 'fa-times-circle'
            suffix = f', {n_warnings} warning{"s" if n_warnings != 1 else ""}' if n_warnings else ''
            b_title = f'{n_issues} issue{"s" if n_issues != 1 else ""} found{suffix}'
        elif n_warnings:
            b_cls, b_icon = 'alert-warning', 'fa-exclamation-triangle'
            b_title = f'{n_warnings} warning{"s" if n_warnings != 1 else ""} — no critical issues'
        else:
            b_cls, b_icon = 'alert-success', 'fa-check-circle'
            b_title = 'All checks passed — no issues found'

        banner = (
            f'<div class="alert {b_cls} d-flex align-items-center gap-3 mb-3" role="alert">'
            f'<i class="fa fa-2x {b_icon} flex-shrink-0"/>'
            f'<div>'
            f'<div class="fw-bold">{b_title}</div>'
            f'<div class="small opacity-75 mt-1">Scanned on {esc(fields.Datetime.to_string(scan_time))} &nbsp;·&nbsp; {esc(self.name)}</div>'
            f'</div></div>'
        )

        # ── Issues / warnings lists ───────────────────────────────────────────
        def _list_group(items, item_cls):
            rows = ''.join(
                f'<div class="list-group-item {item_cls} d-flex align-items-start gap-3 py-3">'
                f'<i class="fa {ico} fa-lg mt-1 flex-shrink-0"/>'
                f'<div><div class="fw-semibold">{ttl}</div>'
                f'<div class="small mt-1 text-body-secondary">{dtl}</div></div></div>'
                for ico, ttl, dtl in items
            )
            return f'<div class="list-group shadow-sm mb-3">{rows}</div>'

        issues_block = ''
        if issues:
            issues_block = (
                '<div class="mb-1"><span class="fw-bold text-danger">'
                f'<i class="fa fa-times-circle me-1"/>Issues ({n_issues})</span></div>'
                + _list_group(issues, 'list-group-item-danger')
            )
        warnings_block = ''
        if warnings:
            warnings_block = (
                '<div class="mb-1"><span class="fw-bold text-warning">'
                f'<i class="fa fa-exclamation-triangle me-1"/>Warnings ({n_warnings})</span></div>'
                + _list_group(warnings, 'list-group-item-warning')
            )

        # ── Stats cards (live data from fetch, not stored fields) ─────────────
        stats_block = ''
        if fetch_result.get('ok'):
            license_rec = self.license_id
            limit_val = str(license_rec.max_employees) if license_rec else '—'

            # Employee count color
            if license_rec:
                _hard = license_rec.max_employees + license_rec.employee_overage_allowed
                if emp > _hard:
                    emp_color = 'text-danger'
                elif emp > license_rec.max_employees:
                    emp_color = 'text-warning'
                else:
                    emp_color = 'text-success'
            else:
                emp_color = 'text-secondary'

            # Installed modules color — red if any required module is missing
            if license_rec and license_rec.module_ids:
                required = {m.technical_name for m in license_rec.module_ids if m.technical_name}
                modules_color = 'text-success' if required.issubset(installed_names) else 'text-danger'
            else:
                modules_color = 'text-success'

            def _card(value, label, color, col='col-6 col-md-3'):
                return (
                    f'<div class="{col}">'
                    f'<div class="border rounded-3 p-3 text-center bg-light">'
                    f'<div class="h3 mb-0 fw-bold {color}">{value}</div>'
                    f'<div class="small text-muted mt-1">{label}</div>'
                    f'</div></div>'
                )

            stats_block = (
                '<hr class="my-3"/>'
                '<div class="small text-muted mb-2 fw-semibold">LIVE SERVER STATS (fetched now)</div>'
                # Row 1 — key metrics
                '<div class="row g-2 mb-2">'
                + _card(emp,                    'Employees',          emp_color)
                + _card(active_users,           'Active Users (30d)', 'text-info')
                + _card(limit_val,              'Employee Limit',     'text-dark')
                + _card(len(installed_modules), 'Installed Modules',  modules_color)
                + '</div>'
                # Row 2 — Odoo user breakdown
                '<div class="small text-muted mb-2 fw-semibold mt-3">ODOO USERS</div>'
                '<div class="row g-2">'
                + _card(odoo_users,      'Total Odoo Users', 'text-primary')
                + _card(internal_users,  'Internal',         'text-success')
                + _card(portal_users,    'Portal',           'text-info')
                + _card(public_users,    'Public',           'text-secondary')
                + _card(archived_users,  'Archived',         'text-muted',    col='col-6 col-md-2')
                + '</div>'
            )

        html = f'<div class="p-3">{banner}{issues_block}{warnings_block}{stats_block}</div>'
        self.sudo().write({'scan_html': html, 'scan_date': scan_time})

    # ── Internal sync ─────────────────────────────────────────────────────────

    def _sync_stats(self):
        """
        Fetch stats from the client server's /ess/api/stats endpoint.
        Returns a result dict: {'ok': True, ...} or {'ok': False, 'error_type': ..., 'message': ...}.
        Always writes last_sync_* fields regardless of outcome.
        """
        self.ensure_one()
        stats_url = self._normalize_url(self.url) + '/ess/api/stats'
        headers = {}
        if self.connection_key:
            headers['X-ESS-Admin-Key'] = self.connection_key

        def _write_status(sync_status, error_msg, server_status=None):
            old_status = self.server_status
            vals = {
                'last_sync_date': fields.Datetime.now(),
                'last_sync_status': sync_status,
                'last_sync_error': error_msg or False,
            }
            if server_status:
                vals['server_status'] = server_status
            self.sudo().write(vals)
            if server_status and server_status != old_status:
                self.sudo()._log_history(old_status, server_status, error_msg, source='sync')

        try:
            resp = requests.get(stats_url, headers=headers, timeout=15)

            if resp.status_code == 401:
                msg = (
                    'Authentication failed (401). '
                    'The connection key on this server record does not match the key '
                    'set in ESS Client → Configuration → Settings. '
                    'Regenerate the key and update both sides.'
                )
                _write_status('failed', msg)
                return {'ok': False, 'error_type': 'AUTH_FAILED', 'message': msg}

            if resp.status_code == 404:
                msg = (
                    'Stats endpoint not found (404). '
                    'Confirm that ess_hr_client is installed on the client server '
                    'and that the server URL is correct (%s).' % self.url
                )
                _write_status('failed', msg)
                return {'ok': False, 'error_type': 'ENDPOINT_NOT_FOUND', 'message': msg}

            if resp.status_code >= 500:
                msg = (
                    'The client server returned an internal error (%d). '
                    'Check the Odoo logs on the client server for details.' % resp.status_code
                )
                _write_status('failed', msg)
                return {'ok': False, 'error_type': 'SERVER_ERROR', 'message': msg}

            if resp.status_code != 200:
                msg = 'Unexpected HTTP response: %d %s.' % (resp.status_code, resp.reason)
                _write_status('failed', msg)
                return {'ok': False, 'error_type': 'HTTP_ERROR', 'message': msg}

            data = resp.json()
            if not data.get('success'):
                err = data.get('error', {})
                msg = 'Client returned a failure: %s' % (err.get('message') or str(data))
                _write_status('failed', msg)
                return {'ok': False, 'error_type': 'RESPONSE_ERROR', 'message': msg}

            stats = data.get('data', {})
            employee_count = int(stats.get('employee_count', 0))
            active_user_count = int(stats.get('active_user_count', 0))
            # Write counts; server_status is set below depending on the limit check.
            self.sudo().write({
                'employee_count': employee_count,
                'active_user_count': active_user_count,
                'odoo_user_count': int(stats.get('odoo_user_count', 0)),
                'internal_user_count': int(stats.get('internal_user_count', 0)),
                'portal_user_count': int(stats.get('portal_user_count', 0)),
                'public_user_count': int(stats.get('public_user_count', 0)),
                'archived_user_count': int(stats.get('archived_user_count', 0)),
                'last_sync_date': fields.Datetime.now(),
                'last_sync_status': 'success',
                'last_sync_error': False,
            })
            # Sync installed modules — full replace
            self.sudo().module_ids.unlink()
            modules_data = stats.get('installed_modules', [])
            if modules_data:
                self.env['ess.server.module'].sudo().create([
                    {
                        'server_id': self.id,
                        'module_name': m.get('name', ''),
                        'technical_name': m.get('technical_name', ''),
                        'version': m.get('version', ''),
                    }
                    for m in modules_data
                ])
            self._check_license_modules()
            limit_exceeded = self._check_employee_limit(employee_count)
            if not limit_exceeded:
                old_status = self.server_status
                self.sudo().write({'server_status': 'active'})
                if old_status != 'active':
                    self.sudo()._log_history(old_status, 'active', 'Sync successful — server is reachable.', source='sync')
            return {
                'ok': True,
                'employee_count': employee_count,
                'active_user_count': active_user_count,
                'limit_exceeded': limit_exceeded,
            }

        except requests.exceptions.ConnectionError:
            msg = (
                'Cannot reach the server at %s. '
                'Check that the URL is correct and the Odoo server is running.' % self.url
            )
            _write_status('unreachable', msg, server_status='unreachable')
            self._deactivate_license('Server unreachable: %s' % self.url)
            return {'ok': False, 'error_type': 'UNREACHABLE', 'message': msg}

        except requests.exceptions.Timeout:
            msg = (
                'Connection timed out after 15 seconds. '
                'The server at %s is not responding.' % self.url
            )
            _write_status('unreachable', msg, server_status='unreachable')
            self._deactivate_license('Server timed out: %s' % self.url)
            return {'ok': False, 'error_type': 'TIMEOUT', 'message': msg}

        except Exception as exc:
            msg = 'Unexpected error during sync: %s' % str(exc)
            _write_status('failed', msg)
            _logger.error('ESS Admin: stats sync failed for %s: %s', self.url, exc)
            return {'ok': False, 'error_type': 'UNEXPECTED', 'message': msg}

    def _check_license_modules(self):
        """
        Compare the license's Allowed Modules (ess.module.technical_name) against
        the modules installed on this server (ess.server.module.technical_name).
        Writes a formatted HTML report into module_check_html.
        """
        self.ensure_one()
        license_rec = self.license_id
        if not license_rec or not license_rec.module_ids:
            self.sudo().write({'module_check_html': False})
            return

        allowed = [m for m in license_rec.module_ids if m.technical_name]
        if not allowed:
            self.sudo().write({'module_check_html': False})
            return

        installed_names = {m.technical_name for m in self.module_ids if m.technical_name}
        missing = [m for m in allowed if m.technical_name not in installed_names]
        installed_ok = [m for m in allowed if m.technical_name in installed_names]

        if not missing:
            html = (
                '<div class="alert alert-success mb-0">'
                '<strong>&#10003; All allowed modules are installed on this server.</strong>'
                '</div>'
            )
        else:
            rows = ''
            for m in missing:
                rows += (
                    '<tr class="table-danger">'
                    f'<td>{m.name}</td>'
                    f'<td><code>{m.technical_name}</code></td>'
                    '<td><span class="badge text-bg-danger">Not Installed</span></td>'
                    '</tr>'
                )
            for m in installed_ok:
                rows += (
                    '<tr class="table-success">'
                    f'<td>{m.name}</td>'
                    f'<td><code>{m.technical_name}</code></td>'
                    '<td><span class="badge text-bg-success">Installed</span></td>'
                    '</tr>'
                )
            html = (
                f'<div class="alert alert-danger mb-3">'
                f'<strong>{len(missing)} of {len(allowed)} allowed module(s) are not installed on this server:</strong>'
                f'</div>'
                f'<table class="table table-sm table-bordered table-hover">'
                f'<thead class="table-dark">'
                f'<tr><th>Allowed Module</th><th>Technical Name</th><th>Status</th></tr>'
                f'</thead>'
                f'<tbody>{rows}</tbody>'
                f'</table>'
            )
        self.sudo().write({'module_check_html': html})

    def _check_employee_limit(self, employee_count):
        """Deactivate this server (and the license if still active) when the limit is exceeded."""
        license_rec = self.license_id
        if not license_rec:
            return False
        limit = license_rec.max_employees + license_rec.employee_overage_allowed
        if employee_count > limit:
            reason = (
                'Employee limit exceeded: %d employees found, limit is %d '
                '(max %d + overage allowed %d).'
            ) % (employee_count, limit, license_rec.max_employees, license_rec.employee_overage_allowed)
            old_status = self.server_status
            if old_status != 'deactivated':
                self.sudo()._log_history(old_status, 'deactivated', reason, source='sync')
            self.sudo().write({'server_status': 'deactivated'})
            self._deactivate_license(reason)
            return True
        return False

    def _deactivate_license(self, reason):
        """Deactivate the license and ALL servers linked to it."""
        license_rec = self.license_id
        if not license_rec or not license_rec.active:
            return
        for server in license_rec.server_ids:
            if server.server_status != 'deactivated':
                server.sudo()._log_history(server.server_status, 'deactivated', reason, source='sync')
        license_rec.sudo()._log_history('active', 'inactive', reason, source='sync')
        license_rec.sudo().write({
            'active': False,
            'deactivation_reason': reason,
            'deactivation_date': fields.Datetime.now(),
        })
        license_rec.server_ids.sudo().write({'server_status': 'deactivated'})
        _logger.warning('ESS Admin: license %s deactivated — %s', license_rec.name, reason)

    def _log_history(self, old_status, new_status, reason, source='sync'):
        """Record a server status change. No-op if status did not change."""
        self.ensure_one()
        if old_status == new_status:
            return
        self.env['ess.server.history'].sudo().create({
            'server_id': self.id,
            'date': fields.Datetime.now(),
            'old_status': old_status,
            'new_status': new_status,
            'reason': (reason or '').strip() or False,
            'source': source,
        })

    @api.model
    def _normalize_url(self, url):
        return (url or '').strip().rstrip('/')

    # ── Scheduled action entry point ──────────────────────────────────────────

    @api.model
    def cron_sync_all_stats(self):
        """Called by the daily scheduled action — syncs all non-deactivated servers."""
        servers = self.sudo().search([('server_status', '!=', 'deactivated')])
        for server in servers:
            try:
                server._sync_stats()
            except Exception as exc:
                _logger.error('ESS Admin cron: error syncing %s: %s', server.url, exc)
