from . import test_license
from . import test_auth
from . import test_attendance
from . import test_leave
from . import test_payslip
from . import test_expense
from . import test_loan
from . import test_advance_salary
from . import test_hr_services
from . import test_tasks
